/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoDeDatos.LaboratorioData;
import entidades.Laboratorio;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author valef
 */
public class AdministracionLaboratorios extends javax.swing.JFrame {

  private LaboratorioData data;
  private final String formatoCuit = "^\\d+-\\d+-\\d+$";

  /**
   * Creates new form AdministracionLaboratorios
   */
  public AdministracionLaboratorios() {
    data = new LaboratorioData();
    initComponents();
    initButtons();
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        cuit = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        pais = new javax.swing.JTextField();
        domicilio = new javax.swing.JTextField();
        buscarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nuevoBtn = new javax.swing.JButton();
        guardarBtn = new javax.swing.JButton();
        modificarBtn = new javax.swing.JButton();
        eliminarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 380, 10));
        getContentPane().add(cuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 220, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel5.setText("Dom. comercial:");

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel4.setText("Pais:");

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel2.setText("CUIT:");

        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarBtn))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(domicilio))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pais))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(buscarBtn))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 425, 220));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administración de Laboratorios");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 400, -1));

        nuevoBtn.setText("Nuevo");
        nuevoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoBtnActionPerformed(evt);
            }
        });
        jPanel1.add(nuevoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(guardarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        modificarBtn.setText("Modificar");
        modificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(modificarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        eliminarBtn.setText("Eliminar");
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 420, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
    try {
      if (cuitValido()) {
        Laboratorio laboratorio = data.obtenerLaboratorio(cuit.getText());
        if (laboratorio == null) {
          JOptionPane.showMessageDialog(null, "No se encontró un laboratorio");
        } else {
          cuit.setEditable(false);
          nombre.setText(laboratorio.getNomLaboratorio());
          nombre.setEditable(false);
          pais.setText(laboratorio.getPais());
          pais.setEditable(false);
          domicilio.setText(laboratorio.getDomComercial());
          domicilio.setEditable(false);

          buscarBtn.setEnabled(false);
          modificarBtn.setEnabled(true);
          eliminarBtn.setEnabled(true);
          nuevoBtn.setEnabled(true);
          guardarBtn.setEnabled(false);
        }
      }
    } catch (SQLException ex) {
      Logger.getLogger(AdministracionLaboratorios.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null, "Ocurrió un error en la base de datos");
    }
  }//GEN-LAST:event_buscarBtnActionPerformed

  private void nuevoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoBtnActionPerformed
    cuit.setEditable(true);
    cuit.setText("");
    nombre.setEditable(true);
    nombre.setText("");
    pais.setEditable(true);
    pais.setText("");
    domicilio.setEditable(true);
    domicilio.setText("");

    buscarBtn.setEnabled(true);
    guardarBtn.setEnabled(true);
    nuevoBtn.setEnabled(true);
    modificarBtn.setEnabled(false);
    eliminarBtn.setEnabled(false);
  }//GEN-LAST:event_nuevoBtnActionPerformed

  private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
    try {
      data.borrarLaboratorio(cuit.getText());
      JOptionPane.showMessageDialog(null, "Se eliminó con éxito");

      cuit.setEditable(true);
      cuit.setText("");
      nombre.setEditable(true);
      nombre.setText("");
      pais.setEditable(true);
      pais.setText("");
      domicilio.setEditable(true);
      domicilio.setText("");

      buscarBtn.setEnabled(true);
      guardarBtn.setEnabled(true);
      nuevoBtn.setEnabled(true);
      modificarBtn.setEnabled(false);
      eliminarBtn.setEnabled(false);
    } catch (SQLException ex) {
      Logger.getLogger(AdministracionLaboratorios.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null, "Ocurrió un error en la base de datos");
    }
  }//GEN-LAST:event_eliminarBtnActionPerformed

  private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
    try {
      if (camposCompletos() && cuitValido()) {
        Laboratorio laboratorio = new Laboratorio();
        laboratorio.setCuit(cuit.getText());
        laboratorio.setNomLaboratorio(nombre.getText());
        laboratorio.setPais(pais.getText());
        laboratorio.setDomComercial(domicilio.getText());

        if (data.existeLaboratorio(cuit.getText())) {
          if(eliminarBtn.isEnabled()){
            data.actualizarLaboratorio(laboratorio);
            JOptionPane.showMessageDialog(null, "Se actualizo laboratorio con exito!");
            
            cuit.setEditable(false);
            pais.setEditable(false);
            nombre.setEditable(false);
            domicilio.setEditable(false);

            guardarBtn.setEnabled(false);
            modificarBtn.setEnabled(true);
            nuevoBtn.setEnabled(true);
            eliminarBtn.setEnabled(true);
            buscarBtn.setEnabled(false);
          }else{
            JOptionPane.showMessageDialog(null, "Ya existe un laboratorio con el CUIT ingresado");  
            
            cuit.setEditable(false);
            pais.setEditable(false);
            nombre.setEditable(false);
            domicilio.setEditable(false);

            guardarBtn.setEnabled(false);
            modificarBtn.setEnabled(false);
            nuevoBtn.setEnabled(true);
            eliminarBtn.setEnabled(false);
            buscarBtn.setEnabled(false);
          }
        } else {
          data.guardarLaboratorio(laboratorio);
          JOptionPane.showMessageDialog(null, "Se guardó laboratorio con éxito!");
          
          cuit.setEditable(false);
        pais.setEditable(false);
        nombre.setEditable(false);
        domicilio.setEditable(false);

        guardarBtn.setEnabled(false);
        modificarBtn.setEnabled(true);
        nuevoBtn.setEnabled(true);
        eliminarBtn.setEnabled(true);
        buscarBtn.setEnabled(false);
        }        
      }
    } catch (SQLException ex) {
      Logger.getLogger(AdministracionLaboratorios.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null, "Ocurrio un error en la base de datos!");
    }
  }//GEN-LAST:event_guardarBtnActionPerformed

  private void modificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnActionPerformed
    nombre.setEditable(true);
    pais.setEditable(true);
    domicilio.setEditable(true);

    guardarBtn.setEnabled(true);
    nuevoBtn.setEnabled(true);
    eliminarBtn.setEnabled(true);
    buscarBtn.setEnabled(false);
    modificarBtn.setEnabled(false);
  }//GEN-LAST:event_modificarBtnActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(AdministracionLaboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(AdministracionLaboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(AdministracionLaboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(AdministracionLaboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new AdministracionLaboratorios().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarBtn;
    private javax.swing.JTextField cuit;
    private javax.swing.JTextField domicilio;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton modificarBtn;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton nuevoBtn;
    private javax.swing.JTextField pais;
    // End of variables declaration//GEN-END:variables

  private boolean camposCompletos() {
    boolean completos = noEmpty(nombre) && noEmpty(cuit) && noEmpty(domicilio) && noEmpty(pais);
    if (!completos) {
      JOptionPane.showMessageDialog(null, "Hay campos incompletos!\nPara avanzar, complete.");
    }
    return completos;
  }

  private boolean noEmpty(JTextField textField) {
    return textField != null && textField.getText() != null && !textField.getText().equalsIgnoreCase("");
  }

  private void initButtons() {
    eliminarBtn.setEnabled(false);
    modificarBtn.setEnabled(false);
  }

  private boolean cuitValido() {
    boolean valido = Pattern.compile(formatoCuit).matcher(cuit.getText()).matches();
    if (!valido) {
      JOptionPane.showMessageDialog(null, "Ingrese un cuit valido!");
    }
    return valido;
  }
}
