/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoDeDatos.LaboratorioData;
import entidades.Laboratorio;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author valef
 */
public class AdministracionLaboratorios extends javax.swing.JFrame {

  private LaboratorioData data;
  private final String formatoCuit = "^\\d+-\\d+-\\d+$";

  /**
   * Creates new form AdministracionLaboratorios
   */
  public AdministracionLaboratorios() {
    data = new LaboratorioData();
    initComponents();
    initButtons();
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    cuit = new javax.swing.JTextField();
    nombre = new javax.swing.JTextField();
    pais = new javax.swing.JTextField();
    domicilio = new javax.swing.JTextField();
    buscarBtn = new javax.swing.JButton();
    guardarBtn = new javax.swing.JButton();
    eliminarBtn = new javax.swing.JButton();
    nuevoBtn = new javax.swing.JButton();
    modificarBtn = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setResizable(false);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jLabel1.setText("Administración de Laboratorios");

    jLabel2.setText("CUIT:");

    jLabel3.setText("Nombre:");

    jLabel4.setText("Pais:");

    jLabel5.setText("Domicilio comercial:");

    buscarBtn.setText("Buscar");
    buscarBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buscarBtnActionPerformed(evt);
      }
    });

    guardarBtn.setText("Guardar");
    guardarBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        guardarBtnActionPerformed(evt);
      }
    });

    eliminarBtn.setText("Eliminar");
    eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        eliminarBtnActionPerformed(evt);
      }
    });

    nuevoBtn.setText("Nuevo");
    nuevoBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nuevoBtnActionPerformed(evt);
      }
    });

    modificarBtn.setText("Modificar");
    modificarBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        modificarBtnActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(75, 75, 75)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jSeparator1))
            .addGap(25, 25, 25))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(48, 48, 48)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel2)
              .addComponent(jLabel3)
              .addComponent(jLabel4)
              .addComponent(jLabel5)
              .addComponent(nuevoBtn))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(cuit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(pais, javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(domicilio, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27)
                .addComponent(buscarBtn))
              .addGroup(layout.createSequentialGroup()
                .addComponent(guardarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modificarBtn)
                .addGap(52, 52, 52)
                .addComponent(eliminarBtn)))))
        .addContainerGap(62, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(37, 37, 37)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(cuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2)
          .addComponent(buscarBtn))
        .addGap(38, 38, 38)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabel3)
          .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(39, 39, 39)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addGap(36, 36, 36)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(guardarBtn)
          .addComponent(eliminarBtn)
          .addComponent(nuevoBtn)
          .addComponent(modificarBtn))
        .addGap(20, 20, 20))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
    try {
      if (cuitValido()) {
        Laboratorio laboratorio = data.obtenerLaboratorio(cuit.getText());
        if (laboratorio == null) {
          JOptionPane.showMessageDialog(null, "No se encontro laboratorio!");
        } else {
          cuit.setEditable(false);
          nombre.setText(laboratorio.getNomLaboratorio());
          nombre.setEditable(false);
          pais.setText(laboratorio.getPais());
          pais.setEditable(false);
          domicilio.setText(laboratorio.getDomComercial());
          domicilio.setEditable(false);

          buscarBtn.setEnabled(false);
          modificarBtn.setEnabled(true);
          eliminarBtn.setEnabled(true);
          nuevoBtn.setEnabled(true);
          guardarBtn.setEnabled(false);
        }
      }
    } catch (SQLException ex) {
      Logger.getLogger(AdministracionLaboratorios.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null, "Ocurrio un error en la base de datos!");
    }
  }//GEN-LAST:event_buscarBtnActionPerformed

  private void nuevoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoBtnActionPerformed
    cuit.setEditable(true);
    cuit.setText("");
    nombre.setEditable(true);
    nombre.setText("");
    pais.setEditable(true);
    pais.setText("");
    domicilio.setEditable(true);
    domicilio.setText("");

    buscarBtn.setEnabled(true);
    guardarBtn.setEnabled(true);
    nuevoBtn.setEnabled(true);
    modificarBtn.setEnabled(false);
    eliminarBtn.setEnabled(false);
  }//GEN-LAST:event_nuevoBtnActionPerformed

  private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
    try {
      data.borrarLaboratorio(cuit.getText());
      JOptionPane.showMessageDialog(null, "Se elimino con exito!");

      cuit.setEditable(true);
      cuit.setText("");
      nombre.setEditable(true);
      nombre.setText("");
      pais.setEditable(true);
      pais.setText("");
      domicilio.setEditable(true);
      domicilio.setText("");

      buscarBtn.setEnabled(true);
      guardarBtn.setEnabled(true);
      nuevoBtn.setEnabled(true);
      modificarBtn.setEnabled(false);
      eliminarBtn.setEnabled(false);
    } catch (SQLException ex) {
      Logger.getLogger(AdministracionLaboratorios.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null, "Ocurrio un error en la base de datos!");
    }
  }//GEN-LAST:event_eliminarBtnActionPerformed

  private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
    try {
      if (camposCompletos() && cuitValido()) {
        Laboratorio laboratorio = new Laboratorio();
        laboratorio.setCuit(cuit.getText());
        laboratorio.setNomLaboratorio(nombre.getText());
        laboratorio.setPais(pais.getText());
        laboratorio.setDomComercial(domicilio.getText());

        if (data.existeLaboratorio(cuit.getText())) {
          data.actualizarLaboratorio(laboratorio);
          JOptionPane.showMessageDialog(null, "Se actualizo laboratorio con exito!");
        } else {
          data.guardarLaboratorio(laboratorio);
          JOptionPane.showMessageDialog(null, "Se guardo laboratorio con exito!");
        }

        cuit.setEditable(false);
        pais.setEditable(false);
        nombre.setEditable(false);
        domicilio.setEditable(false);

        guardarBtn.setEnabled(false);
        modificarBtn.setEnabled(true);
        nuevoBtn.setEnabled(true);
        eliminarBtn.setEnabled(true);
        buscarBtn.setEnabled(false);
      }
    } catch (SQLException ex) {
      Logger.getLogger(AdministracionLaboratorios.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null, "Ocurrio un error en la base de datos!");
    }
  }//GEN-LAST:event_guardarBtnActionPerformed

  private void modificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnActionPerformed
    nombre.setEditable(true);
    pais.setEditable(true);
    domicilio.setEditable(true);

    guardarBtn.setEnabled(true);
    nuevoBtn.setEnabled(true);
    eliminarBtn.setEnabled(true);
    buscarBtn.setEnabled(false);
    modificarBtn.setEnabled(false);
  }//GEN-LAST:event_modificarBtnActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(AdministracionLaboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(AdministracionLaboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(AdministracionLaboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(AdministracionLaboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new AdministracionLaboratorios().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buscarBtn;
  private javax.swing.JTextField cuit;
  private javax.swing.JTextField domicilio;
  private javax.swing.JButton eliminarBtn;
  private javax.swing.JButton guardarBtn;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JButton modificarBtn;
  private javax.swing.JTextField nombre;
  private javax.swing.JButton nuevoBtn;
  private javax.swing.JTextField pais;
  // End of variables declaration//GEN-END:variables

  private boolean camposCompletos() {
    boolean completos = noEmpty(nombre) && noEmpty(cuit) && noEmpty(domicilio) && noEmpty(pais);
    if (!completos) {
      JOptionPane.showMessageDialog(null, "Hay campos incompletos!\nPara avanzar, complete.");
    }
    return completos;
  }

  private boolean noEmpty(JTextField textField) {
    return textField != null && textField.getText() != null && !textField.getText().equalsIgnoreCase("");
  }

  private void initButtons() {
    eliminarBtn.setEnabled(false);
    modificarBtn.setEnabled(false);
  }

  private boolean cuitValido() {
    boolean valido = Pattern.compile(formatoCuit).matcher(cuit.getText()).matches();
    if (!valido) {
      JOptionPane.showMessageDialog(null, "Ingrese un cuit valido!");
    }
    return valido;
  }
}
