/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoDeDatos.CitaVacunacion2Data;
import entidades.CitaVacunacion2;
import entidades.Ciudadano;
import entidades.Vacuna;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Elio Flores
 */
public class AdministracionTurnos extends javax.swing.JFrame {

  private final CitaVacunacion2Data citaVacunacionData;
  private List<Ciudadano> ciudadanos;
  private List<Vacuna> vacunas;
  private boolean recienGuarde = false;

  /**
   * Creates new form TurnosABM
   */
  public AdministracionTurnos() {
    this.citaVacunacionData = new CitaVacunacion2Data();
    initComponents();
    initButtons();
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        nuevoBtn = new javax.swing.JButton();
        guardarBtn = new javax.swing.JButton();
        eliminarBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        dniLabel8 = new javax.swing.JLabel();
        dniLabel11 = new javax.swing.JLabel();
        pais = new javax.swing.JTextField();
        dniLabel12 = new javax.swing.JLabel();
        domicilio = new javax.swing.JTextField();
        dniLabel13 = new javax.swing.JLabel();
        dniLabel14 = new javax.swing.JLabel();
        nombreLaboratorio = new javax.swing.JTextField();
        dniLabel15 = new javax.swing.JLabel();
        cuit = new javax.swing.JTextField();
        codCitaLabel = new javax.swing.JLabel();
        codigoCita = new javax.swing.JTextField();
        buscarBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        dniLabel = new javax.swing.JLabel();
        dniLabel19 = new javax.swing.JLabel();
        nombreCiudadano = new javax.swing.JTextField();
        separador3 = new javax.swing.JSeparator();
        separador4 = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        listaCiudadanos = new javax.swing.JComboBox<>();
        dniLabel1 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        dniLabel2 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        celular = new javax.swing.JTextField();
        dniLabel3 = new javax.swing.JLabel();
        colocada = new javax.swing.JCheckBox();
        dniLabel4 = new javax.swing.JLabel();
        separador5 = new javax.swing.JSeparator();
        patologia = new javax.swing.JTextField();
        fecha = new com.toedter.calendar.JDateChooser();
        horario = new javax.swing.JComboBox<>();
        sede = new javax.swing.JComboBox<>();
        dniLabel5 = new javax.swing.JLabel();
        ambito = new javax.swing.JTextField();
        listaVacunas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        dniLabel6 = new javax.swing.JLabel();
        serie = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        caducidad = new javax.swing.JTextField();
        medida = new javax.swing.JTextField();
        dniLabel7 = new javax.swing.JLabel();
        separador1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        titulo.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Administracion de citas de vacunacion");

        nuevoBtn.setText("Limpiar");
        nuevoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoBtnActionPerformed(evt);
            }
        });

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        eliminarBtn.setText("Eliminar");
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        dniLabel8.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        dniLabel8.setText("Marca:");

        dniLabel11.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        dniLabel11.setText("Medida:");

        pais.setEditable(false);
        pais.setBackground(new java.awt.Color(255, 255, 255));

        dniLabel12.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        dniLabel12.setText("Pais:");

        domicilio.setEditable(false);
        domicilio.setBackground(new java.awt.Color(255, 255, 255));

        dniLabel13.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        dniLabel13.setText("Domicilio:");

        dniLabel14.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        dniLabel14.setText("Laboratorio:");

        nombreLaboratorio.setEditable(false);
        nombreLaboratorio.setBackground(new java.awt.Color(255, 255, 255));

        dniLabel15.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        dniLabel15.setText("CUIT:");

        cuit.setEditable(false);
        cuit.setBackground(new java.awt.Color(255, 255, 255));

        codCitaLabel.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        codCitaLabel.setText("Codigo cita:");

        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel4.setText("Sede:");

        dniLabel.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        dniLabel.setText("Nombre:");

        dniLabel19.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        dniLabel19.setText("Fecha cita:");

        nombreCiudadano.setEditable(false);
        nombreCiudadano.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel1.setText("Ciudadano:");

        listaCiudadanos.setModel(new javax.swing.DefaultComboBoxModel<>(ciudadanos()));
        listaCiudadanos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaCiudadanosItemStateChanged(evt);
            }
        });

        dniLabel1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        dniLabel1.setText("DNI:");

        dni.setEditable(false);
        dni.setBackground(new java.awt.Color(255, 255, 255));

        dniLabel2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        dniLabel2.setText("Email:");

        email.setEditable(false);
        email.setBackground(new java.awt.Color(255, 255, 255));

        celular.setEditable(false);
        celular.setBackground(new java.awt.Color(255, 255, 255));

        dniLabel3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        dniLabel3.setText("Celular:");

        colocada.setText("Vacuna aplicada");
        colocada.setEnabled(false);

        dniLabel4.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        dniLabel4.setText("Patologia:");

        patologia.setEditable(false);
        patologia.setBackground(new java.awt.Color(255, 255, 255));

        horario.setModel(new javax.swing.DefaultComboBoxModel<>(horarios()));

        sede.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sucursal 1", "Sucursal 2", "Sucursal 3", "Sucursal 4" }));

        dniLabel5.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        dniLabel5.setText("Trabajo:");

        ambito.setEditable(false);
        ambito.setBackground(new java.awt.Color(255, 255, 255));

        listaVacunas.setModel(new javax.swing.DefaultComboBoxModel<>(vacunas()));
        listaVacunas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaVacunasItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel2.setText("Vacuna:");

        dniLabel6.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        dniLabel6.setText("Nro. de serie:");

        serie.setEditable(false);
        serie.setBackground(new java.awt.Color(255, 255, 255));

        marca.setEditable(false);
        marca.setBackground(new java.awt.Color(255, 255, 255));

        caducidad.setEditable(false);
        caducidad.setBackground(new java.awt.Color(255, 255, 255));

        medida.setEditable(false);
        medida.setBackground(new java.awt.Color(255, 255, 255));

        dniLabel7.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        dniLabel7.setText("Expiración:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(dniLabel11)
                                        .addGap(57, 57, 57)
                                        .addComponent(medida)
                                        .addGap(56, 56, 56))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(dniLabel6)
                                        .addGap(26, 26, 26)
                                        .addComponent(serie, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dniLabel8)
                                    .addComponent(dniLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(caducidad, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(marca))
                                .addGap(46, 46, 46))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(37, 37, 37)
                                        .addComponent(listaCiudadanos, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(57, 57, 57)
                                        .addComponent(listaVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dniLabel)
                                            .addComponent(dniLabel2)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(dniLabel4)
                                                .addGap(3, 3, 3)))
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(patologia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(nombreCiudadano, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(60, 60, 60)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(dniLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(celular))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(dniLabel1)
                                                .addGap(35, 35, 35)
                                                .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(dniLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ambito))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(colocada))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(codCitaLabel)
                                        .addGap(38, 38, 38)
                                        .addComponent(codigoCita, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(buscarBtn)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dniLabel13)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(dniLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dniLabel15)
                                    .addComponent(dniLabel12))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pais, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(cuit))
                                .addGap(46, 46, 46))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(separador4, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sede, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(dniLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(horario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(separador5, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarBtn)
                    .addComponent(codCitaLabel))
                .addGap(12, 12, 12)
                .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addComponent(listaCiudadanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniLabel)
                    .addComponent(nombreCiudadano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dniLabel1)
                    .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dniLabel2)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dniLabel3)
                            .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ambito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dniLabel5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dniLabel4)
                            .addComponent(patologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addComponent(listaVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dniLabel6)
                            .addComponent(serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dniLabel8)
                            .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dniLabel11)
                    .addComponent(dniLabel7)
                    .addComponent(caducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(colocada)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(separador4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dniLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dniLabel13)
                            .addComponent(domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dniLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dniLabel12)
                            .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(separador5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(sede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dniLabel19))
                    .addComponent(horario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nuevoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(guardarBtn)
                .addGap(34, 34, 34)
                .addComponent(eliminarBtn)
                .addGap(25, 25, 25))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(titulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBtn)
                    .addComponent(eliminarBtn)
                    .addComponent(nuevoBtn))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
    try {
      if (!citaVacunacionData.existeCitaVacunacion(Integer.parseInt(codigoCita.getText()))) {
        JOptionPane.showMessageDialog(null, "Codigo no existe!");
        return;
      }
      CitaVacunacion2 citaVacunacion = citaVacunacionData.obtenerCitaVacunacion(Integer.parseInt(codigoCita.getText()));
      completarCiudadano(citaVacunacion.getPersona());
      completarVacuna(citaVacunacion.getDosis());
      sede.setSelectedIndex(citaVacunacion.getCentroVacunacion() + 1);
      fecha.setDate(toDate(citaVacunacion.getFechaHoraCita().toLocalDate()));
      horario.setSelectedItem(citaVacunacion.getFechaHoraCita().toLocalTime());

      listaCiudadanos.setEnabled(false);
      listaVacunas.setEnabled(false);

      sede.setEnabled(false);
      horario.setEnabled(false);
      fecha.setEnabled(false);
      codigoCita.setEditable(false);
      buscarBtn.setEnabled(false);
      guardarBtn.setEnabled(false);
      nuevoBtn.setEnabled(true);
      eliminarBtn.setEnabled(true);
    } catch (SQLException ex) {
      Logger.getLogger(AdministracionTurnos.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null, "SQL error!");
    }
  }//GEN-LAST:event_buscarBtnActionPerformed

  private void nuevoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoBtnActionPerformed
    if (recienGuarde) {
      listaVacunas.removeItemAt(listaVacunas.getSelectedIndex());
    }
    codigoCita.setEditable(true);
    limpiarTodo();
    listaCiudadanos.setEnabled(true);
    listaVacunas.setEnabled(true);
    sede.setEnabled(true);
    horario.setEnabled(true);
    fecha.setEnabled(true);
    initButtons();
  }//GEN-LAST:event_nuevoBtnActionPerformed

  private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
    try {
      if (ciudadanoElegido() != null) {
        if (vacunaElegida() == null) {
          if (noHayVacunas()) {
            CitaVacunacion2 citaVacunacion = new CitaVacunacion2();
            citaVacunacion.setPersona(listaCiudadanos.getItemAt(listaCiudadanos.getSelectedIndex()));

            LocalDate hoy = LocalDate.now();
            citaVacunacion.setFechaHoraCita(LocalDateTime.of(hoy.plusDays(20), horario.getItemAt(horario.getSelectedIndex())));
            fecha.setDate(toDate(hoy.plusDays(20)));

            citaVacunacion.setCentroVacunacion(sede.getSelectedIndex() + 1);
            citaVacunacionData.guardarCitaVacunacion(citaVacunacion);
            recienGuarde = true;
            JOptionPane.showMessageDialog(null, "Turno guardado.\nSe debe asignar una vacuna manualmente antes de la fecha de cita!");
            buscarBtn.setEnabled(false);
            guardarBtn.setEnabled(false);
            nuevoBtn.setEnabled(true);
            eliminarBtn.setEnabled(true);
            recienGuarde = true;
          } else {
            JOptionPane.showMessageDialog(null, "Selecciona una vacuna!!!");
          }
        } else {
          if (fecha.getDate() != null) {
            CitaVacunacion2 citaVacunacion = new CitaVacunacion2();
            citaVacunacion.setPersona(listaCiudadanos.getItemAt(listaCiudadanos.getSelectedIndex()));
            citaVacunacion.setDosis(listaVacunas.getItemAt(listaVacunas.getSelectedIndex()));
            citaVacunacion.setFechaHoraCita(LocalDateTime.of(toLocalDate(fecha.getDate()), horario.getItemAt(horario.getSelectedIndex())));
            citaVacunacion.setCentroVacunacion(sede.getSelectedIndex() + 1);
            citaVacunacionData.guardarCitaVacunacion(citaVacunacion);
            recienGuarde = true;
            buscarBtn.setEnabled(false);
            guardarBtn.setEnabled(false);
            nuevoBtn.setEnabled(true);
            eliminarBtn.setEnabled(true);
          } else {
            JOptionPane.showMessageDialog(null, "Elija una fecha para la cita!");
          }
        }
      } else {
        JOptionPane.showMessageDialog(null, "Tiene que elegir ciudadano!");
      }
    } catch (SQLException ex) {
      Logger.getLogger(AdministracionTurnos.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null, "Ocurrio un error!\nControla que la base de datos este funcionando.\nTambien verfica que acepten NULL el campo 'fechaHoraColoca' y 'nroSerieDosis'");
    }
  }//GEN-LAST:event_guardarBtnActionPerformed

  private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
    try {
      citaVacunacionData.borrarCitaVacunacion(Integer.parseInt(codigoCita.getText()));
      limpiarTodo();
      initButtons();
    } catch (SQLException ex) {
      Logger.getLogger(AdministracionTurnos.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_eliminarBtnActionPerformed

  private void listaCiudadanosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaCiudadanosItemStateChanged
    limpiarCiudadano();
    if (ciudadanoElegido() != null) {
      completarCiudadano(ciudadanoElegido());
    }
  }//GEN-LAST:event_listaCiudadanosItemStateChanged

  private void listaVacunasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaVacunasItemStateChanged
    limpiarVacuna();
    if (vacunaElegida() != null) {
      completarVacuna(vacunaElegida());
    }
  }//GEN-LAST:event_listaVacunasItemStateChanged

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(AdministracionTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(AdministracionTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(AdministracionTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(AdministracionTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new AdministracionTurnos().setVisible(true);
      }
    });
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ambito;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JTextField caducidad;
    private javax.swing.JTextField celular;
    private javax.swing.JLabel codCitaLabel;
    private javax.swing.JTextField codigoCita;
    private javax.swing.JCheckBox colocada;
    private javax.swing.JTextField cuit;
    private javax.swing.JTextField dni;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JLabel dniLabel1;
    private javax.swing.JLabel dniLabel11;
    private javax.swing.JLabel dniLabel12;
    private javax.swing.JLabel dniLabel13;
    private javax.swing.JLabel dniLabel14;
    private javax.swing.JLabel dniLabel15;
    private javax.swing.JLabel dniLabel19;
    private javax.swing.JLabel dniLabel2;
    private javax.swing.JLabel dniLabel3;
    private javax.swing.JLabel dniLabel4;
    private javax.swing.JLabel dniLabel5;
    private javax.swing.JLabel dniLabel6;
    private javax.swing.JLabel dniLabel7;
    private javax.swing.JLabel dniLabel8;
    private javax.swing.JTextField domicilio;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JTextField email;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JComboBox<LocalTime> horario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<Ciudadano> listaCiudadanos;
    private javax.swing.JComboBox<Vacuna> listaVacunas;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField medida;
    private javax.swing.JTextField nombreCiudadano;
    private javax.swing.JTextField nombreLaboratorio;
    private javax.swing.JButton nuevoBtn;
    private javax.swing.JTextField pais;
    private javax.swing.JTextField patologia;
    private javax.swing.JComboBox<String> sede;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separador3;
    private javax.swing.JSeparator separador4;
    private javax.swing.JSeparator separador5;
    private javax.swing.JTextField serie;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

  private void initButtons() {
    buscarBtn.setEnabled(true);
    guardarBtn.setEnabled(true);
    nuevoBtn.setEnabled(true);
    eliminarBtn.setEnabled(false);
  }

  private Ciudadano[] ciudadanos() {
    try {
      List<Ciudadano> ciudadanos = citaVacunacionData.listarPersonas();
      ciudadanos.add(0, null);
      return ciudadanos.toArray(new Ciudadano[0]);
    } catch (SQLException ex) {
      Logger.getLogger(AdministracionTurnos.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null, "Error: No se puedo realizar la consulta!");
    }
    return new Ciudadano[0];
  }

  private Vacuna[] vacunas() {
    try {
      List<Vacuna> vacunas = citaVacunacionData.listarVacunasLibres();
      vacunas.add(0, null);
      return vacunas.toArray(new Vacuna[0]);
    } catch (SQLException ex) {
      Logger.getLogger(AdministracionTurnos.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(null, "Error: No se puedo realizar la consulta!");
    }
    return new Vacuna[0];
  }

  private void completarCiudadano(Ciudadano ciudadano) {
    nombreCiudadano.setText(ciudadano.getNomCompleto());
    dni.setText(ciudadano.getDni() + "");
    email.setText(ciudadano.getEmail());
    celular.setText(ciudadano.getCelular());
    patologia.setText(ciudadano.getPatologia());
    ambito.setText(ciudadano.getAmbitoTrabajo());
  }

  private void completarVacuna(Vacuna vacuna) {
    serie.setText(vacuna.getNroSerieDosis() + "");
    medida.setText(vacuna.getMedida() + "");
    caducidad.setText(vacuna.getFechaCaduca().toString());
    colocada.setSelected(vacuna.getColocada());
    nombreLaboratorio.setText(vacuna.getLaboratorio().getNomLaboratorio());
    cuit.setText(vacuna.getLaboratorio().getCuit());
    domicilio.setText(vacuna.getLaboratorio().getDomComercial());
    pais.setText(vacuna.getLaboratorio().getPais());
  }

  private Ciudadano ciudadanoElegido() {
    return listaCiudadanos.getItemAt(listaCiudadanos.getSelectedIndex());
  }

  private Vacuna vacunaElegida() {
    return listaVacunas.getItemAt(listaVacunas.getSelectedIndex());
  }

  private LocalTime[] horarios() {
    LocalTime actual = LocalTime.of(7, 45).plusMinutes(15L);
    List<LocalTime> horariosDisponibles = new ArrayList<>();
    while (actual.isBefore(LocalTime.of(18, 15))) {
      horariosDisponibles.add(actual);
      actual = actual.plusMinutes(15L);
    }
    return horariosDisponibles.toArray(new LocalTime[0]);
  }

  private LocalDate toLocalDate(Date date) {
    return date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
  }

  private Date toDate(LocalDate localDate) {
    return java.util.Date.from(localDate.atStartOfDay()
            .atZone(ZoneId.systemDefault())
            .toInstant());
  }

  private void limpiarCiudadano() {
    dni.setText("");
    nombreCiudadano.setText("");
    email.setText("");
    celular.setText("");
    patologia.setText("");
    ambito.setText("");
  }

  private void limpiarVacuna() {
    serie.setText("");
    medida.setText("");
    caducidad.setText("");
    nombreLaboratorio.setText("");
    cuit.setText("");
    domicilio.setText("");
    pais.setText("");
  }

  private void limpiarTodo() {
    limpiarCiudadano();
    limpiarVacuna();
    codigoCita.setText("");
    fecha.setDate(null);
    sede.setSelectedIndex(0);
    horario.setSelectedIndex(0);
  }

  private boolean noHayVacunas() {
    return listaVacunas.getItemCount() <= 1;
  }
}
