/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoDeDatos.LaboratorioData;
import entidades.Laboratorio;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author valef
 */
public class AdministracionLaboratorios extends javax.swing.JFrame {

  private LaboratorioData data;
  private Laboratorio actual;

  /**
   * Creates new form AdministracionLaboratorios
   */
  public AdministracionLaboratorios() {
    data = new LaboratorioData();
    actual = new Laboratorio();
    initComponents();
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    cuit = new javax.swing.JTextField();
    nombre = new javax.swing.JTextField();
    pais = new javax.swing.JTextField();
    domicilio = new javax.swing.JTextField();
    buscarBtn = new javax.swing.JButton();
    guardarBtn = new javax.swing.JButton();
    eliminarBtn = new javax.swing.JButton();
    limpiarBtn = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setResizable(false);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jLabel1.setText("Administración de Laboratorios");

    jLabel2.setText("CUIT:");

    jLabel3.setText("Nombre:");

    jLabel4.setText("Pais:");

    jLabel5.setText("Domicilio comercial:");

    buscarBtn.setText("Buscar");
    buscarBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buscarBtnActionPerformed(evt);
      }
    });

    guardarBtn.setText("Guardar");
    guardarBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        guardarBtnActionPerformed(evt);
      }
    });

    eliminarBtn.setText("Eliminar");
    eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        eliminarBtnActionPerformed(evt);
      }
    });

    limpiarBtn.setText("Limpiar");
    limpiarBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        limpiarBtnActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(48, 48, 48)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel2)
              .addComponent(jLabel3)
              .addComponent(jLabel4)
              .addComponent(jLabel5))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(cuit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(nombre, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(pais, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(domicilio, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGap(27, 27, 27)
            .addComponent(buscarBtn))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jSeparator1)))
              .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(eliminarBtn))
              .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(guardarBtn)))
            .addGap(25, 25, 25)))
        .addContainerGap(62, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(limpiarBtn)
        .addGap(85, 85, 85))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(37, 37, 37)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(cuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2)
          .addComponent(buscarBtn))
        .addGap(38, 38, 38)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabel3)
          .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(39, 39, 39)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addGap(36, 36, 36)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(guardarBtn)
          .addComponent(eliminarBtn)
          .addComponent(limpiarBtn))
        .addGap(20, 20, 20))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
    try {
      actual = data.obtenerLaboratorio(cuit.getText());
      if (actual == null) {
        JOptionPane.showMessageDialog(null, "Cuit no registrado!");
        actual = new Laboratorio();
      } else {
        nombre.setText(actual.getNomLaboratorio());
        pais.setText(actual.getPais());
        domicilio.setText(actual.getDomComercial());
      }
    } catch (Exception e) {
      JOptionPane.showMessageDialog(null, e.getMessage());
    }
  }//GEN-LAST:event_buscarBtnActionPerformed

  private void limpiarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarBtnActionPerformed
    cuit.setText("");
    nombre.setText("");
    pais.setText("");
    domicilio.setText("");
    actual = new Laboratorio();
  }//GEN-LAST:event_limpiarBtnActionPerformed

  private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
    buscarBtnActionPerformed(null);
    if (actual.getCuit() != null) {
      data.eliminarLaboratorio(actual.getCuit());
    }
  }//GEN-LAST:event_eliminarBtnActionPerformed

  private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
    if (camposCompletos()) {
      actual.setNomLaboratorio(nombre.getText());
      actual.setCuit(cuit.getText());
      actual.setPais(pais.getText());
      actual.setDomComercial(domicilio.getText());
      data.guardarLaboratorio(actual);
    } else {
      JOptionPane.showMessageDialog(null, "Complete todos los datos!");
    }
  }//GEN-LAST:event_guardarBtnActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(AdministracionLaboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(AdministracionLaboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(AdministracionLaboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(AdministracionLaboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new AdministracionLaboratorios().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buscarBtn;
  private javax.swing.JTextField cuit;
  private javax.swing.JTextField domicilio;
  private javax.swing.JButton eliminarBtn;
  private javax.swing.JButton guardarBtn;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JButton limpiarBtn;
  private javax.swing.JTextField nombre;
  private javax.swing.JTextField pais;
  // End of variables declaration//GEN-END:variables

  private boolean camposCompletos() {
    return noEmpty(nombre) || noEmpty(cuit) || noEmpty(domicilio) || noEmpty(pais);
  }

  private boolean noEmpty(JTextField textField) {
    return textField != null && textField.getText() != null && !textField.getText().equalsIgnoreCase("");
  }
}
