/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoDeDatos.CitaVacunacionData;
import accesoDeDatos.CiudadanoData;
import entidades.CitaVacunacion;
import entidades.Ciudadano;
import entidades.Laboratorio;
import entidades.Vacuna;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.Calendar;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.RowSorter;
import javax.swing.RowSorter.SortKey;
import javax.swing.SortOrder;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import usos.EstadoCitaCellRenderer;
import usos.Usos;

/**
 *
 * @author valef
 */
public class CitasXDia extends javax.swing.JFrame {

    private DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Hacer que todas las celdas sean no editables
                return false;
            }
        };
    
    private ArrayList<CitaVacunacion> lista_citas = new ArrayList();
    private CitaVacunacionData data = new CitaVacunacionData();
    private CiudadanoData ciudadata = new CiudadanoData();
    private CitaVacunacion cita_seleccionada = null;
    
    
    /**
     * Creates new form AdministracionCiudadano
     */
    public CitasXDia() {
        initComponents();
        cargarItems();
        setLocationRelativeTo(null);
        detallesBoton.setEnabled(false);
        
        tablaCitas.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (!e.getValueIsAdjusting()) {
                int[] selectedRow = tablaCitas.getSelectedRows();
                if (selectedRow.length == 1) {
                    detallesBoton.setEnabled(true);
                    cita_seleccionada = lista_citas.get(selectedRow[0]);
                } else{
                    detallesBoton.setEnabled(false);
                    cita_seleccionada = null;
                }
            }
        }
        });
        
        cargarArray();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        elegirFecha_field = new com.toedter.calendar.JDateChooser();
        diaHoy_boton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCitas = new javax.swing.JTable();
        detallesBoton = new javax.swing.JButton();
        diaDespues_boton = new javax.swing.JButton();
        diaAnterior_boton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sede_comoBox = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Dia");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Control Interno - Sedes");

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        elegirFecha_field.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        elegirFecha_field.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                elegirFecha_fieldPropertyChange(evt);
            }
        });

        diaHoy_boton.setText("Hoy");
        diaHoy_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaHoy_botonActionPerformed(evt);
            }
        });

        tablaCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaCitas.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(tablaCitas);

        detallesBoton.setText("Detalles");
        detallesBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detallesBotonActionPerformed(evt);
            }
        });

        diaDespues_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaDespues_botonActionPerformed(evt);
            }
        });

        diaAnterior_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaAnterior_botonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Dia");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Sede");

        sede_comoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sede_comoBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sede_comoBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(diaAnterior_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(detallesBoton)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(diaDespues_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(elegirFecha_field, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diaHoy_boton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sede_comoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(elegirFecha_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(diaHoy_boton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                .addComponent(sede_comoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(diaDespues_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(201, 201, 201))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(diaAnterior_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(206, 206, 206)))))
                .addComponent(detallesBoton)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel5))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diaHoy_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaHoy_botonActionPerformed
        Calendar calendario = Calendar.getInstance();
        Date fechaHoy = calendario.getTime();
        elegirFecha_field.setDate(fechaHoy);
    }//GEN-LAST:event_diaHoy_botonActionPerformed

    private void diaDespues_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaDespues_botonActionPerformed
        pasarDias(1);
    }//GEN-LAST:event_diaDespues_botonActionPerformed

    private void diaAnterior_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaAnterior_botonActionPerformed
        pasarDias(-1);
    }//GEN-LAST:event_diaAnterior_botonActionPerformed

    private void elegirFecha_fieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_elegirFecha_fieldPropertyChange
        try{
            if(elegirFecha_field.getDate()==null){
                Calendar calendario = Calendar.getInstance();
                Date fechaHoy = calendario.getTime();
                elegirFecha_field.setDate(fechaHoy);
            }
            
            cargarArray();
            llenarTabla();
        
            Calendar calendario = Calendar.getInstance();
            LocalDate fechaHoy = Usos.convertirDate(calendario.getTime());
            LocalDate fechaCita = Usos.convertirDate(elegirFecha_field.getDate());

            if(fechaHoy.equals(fechaCita)){
                diaHoy_boton.setEnabled(false);        
            } else{
                diaHoy_boton.setEnabled(true);
            }
        }catch(Exception ex){}
    }//GEN-LAST:event_elegirFecha_fieldPropertyChange

    private void detallesBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detallesBotonActionPerformed
        detalles(cita_seleccionada);
    }//GEN-LAST:event_detallesBotonActionPerformed

    private void sede_comoBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sede_comoBoxItemStateChanged
        cargarArray();
        llenarTabla();
    }//GEN-LAST:event_sede_comoBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CitasXDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CitasXDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CitasXDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CitasXDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CitasXDia().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton detallesBoton;
    private javax.swing.JButton diaAnterior_boton;
    private javax.swing.JButton diaDespues_boton;
    private javax.swing.JButton diaHoy_boton;
    private com.toedter.calendar.JDateChooser elegirFecha_field;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> sede_comoBox;
    private javax.swing.JTable tablaCitas;
    // End of variables declaration//GEN-END:variables

    public void cargarItems(){
        sede_comoBox.removeAllItems();
        sede_comoBox.addItem("Sucursal 1");
        sede_comoBox.addItem("Sucursal 2");
        sede_comoBox.addItem("Sucursal 3");
        sede_comoBox.addItem("Sucursal 4");
        
        modelo.addColumn("DNI");
        modelo.addColumn("Horario");
        modelo.addColumn("Dosis");
        modelo.addColumn("Laboratorio");
        modelo.addColumn("Estado");
        
        EstadoCitaCellRenderer estadoRenderer = new EstadoCitaCellRenderer();
        tablaCitas.getColumnModel().getColumn(4).setCellRenderer(estadoRenderer);
                
        tablaCitas.setModel(modelo);
    }
    
    public void pasarDias(int dias){
        try{
            Calendar calendario = Calendar.getInstance();
            Date fecha = elegirFecha_field.getDate();
            calendario.setTime(fecha);
            calendario.add(Calendar.DATE, dias);
            fecha = calendario.getTime();
            elegirFecha_field.setDate(fecha);
        }catch(Exception ex){
            Calendar calendario = Calendar.getInstance();
            Date fechaHoy = calendario.getTime();
            elegirFecha_field.setDate(fechaHoy);
        }
    }
    
    public void cargarArray(){
         Date fecha = elegirFecha_field.getDate();
         lista_citas = data.buscarCitas_porFecha(Usos.convertirDate(fecha), comboBox());
         ordenarArray();
    }
    
    private void limpiarTabla(){
        modelo.setRowCount(0);
    } 
    
    private void llenarTabla() {
    limpiarTabla();
    int i = 0;
    for (CitaVacunacion aux : lista_citas) {
            modelo.addRow(new Object[]{aux.getDni(), aux.getHorario() , aux.getDosis().getMedida(), aux.getDosis().getLaboratorio().getNomLaboratorio(), estadoCita(aux)});
        }
    sortearTabla();
    tablaCitas.setModel(modelo);
  }
    
    private int comboBox(){
        int seleccion = sede_comoBox.getSelectedIndex();
        return seleccion+1;
    }
    
    private void detalles(CitaVacunacion cita){
        Vacuna vacuna = cita.getDosis();        
        Ciudadano persona = ciudadata.buscarCiudadano(cita.getDni());
        Laboratorio lab = vacuna.getLaboratorio();

        
        int aux = cita.getDni();
        String dni = String.valueOf(aux);
        
        Date fecha = cita.getFechaHoraCita();
        
        LocalTime auxo = cita.getHorario();
        String horario = auxo.toString();
        
        aux = cita.getCentroVacunacion();
        String sede = String.valueOf(aux);
        
        double auxx = vacuna.getMedida();
        String medida = String.valueOf(auxx);
        
        aux = vacuna.getNroSerieDosis();
        String nroserie = String.valueOf(aux);
        
        aux = vacuna.getStock();
        String stock = String.valueOf(aux);
        
        String nombre_lab = lab.getNomLaboratorio();
        String cuit = lab.getCuit();
        
        String nombre_persona = persona.getNomCompleto();
        
        aux = persona.getDosis();
        String dosis_aplicados = String.valueOf(aux);
        
        CitaDetalles ventana = new CitaDetalles(dni, dosis_aplicados, fecha, horario, cuit, nombre_lab, medida, nombre_persona, nroserie, sede, stock, estadoCita(cita), cita.getCodCita());
        ventana.setVisible(true);
    }
    
    private void sortearTabla() {
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
    try {
        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<>(modelo);
        tablaCitas.setRowSorter(rowSorter);

        Comparator<LocalTime> localTimeComparator = (lt1, lt2) -> lt1.compareTo(lt2);
        rowSorter.setComparator(1, localTimeComparator);
        ArrayList<RowSorter.SortKey> sortKeys = new ArrayList<>();
        sortKeys.add(new RowSorter.SortKey(1, SortOrder.ASCENDING));
        rowSorter.setSortKeys(sortKeys);
    } catch (Exception e) {}}
    
    private String estadoCita(CitaVacunacion cita){
        
        Calendar calendario = Calendar.getInstance();
        LocalDate fechaHoy = Usos.convertirDate(calendario.getTime());
        LocalDate fechaCita = Usos.convertirDate(elegirFecha_field.getDate());
        
        LocalTime horario_cita = cita.getHorario();
        LocalTime horario_ahora = Usos.obtenerLocalTimeDesdeCalendar(calendario);

        int estadoCita;
        
            if(fechaCita.isBefore(fechaHoy)){                           //antes que hoy
                if(cita.getDosis().getColocada()){
                    estadoCita = 2;
                }else{
                    if(cita.isCitaEstado()){
                        estadoCita = 0;   
                    }else{
                        estadoCita = 3;
                    }
                }
                
            } else if (fechaCita.equals(fechaHoy)){                 //igual a hoy
                if(cita.getDosis().getColocada()){
                    estadoCita = 2;
                }else{
                    if(horario_cita.isBefore(horario_ahora)){
                        if(cita.isCitaEstado()){
                            estadoCita = 0;   
                        }else{
                            estadoCita = 3;
                        }
                    } else{
                        estadoCita = 1;
                    }
                }
            } else {                                                                        //despues de hoy
                if(cita.isCitaEstado()){
                        estadoCita = 1;
                    }else{
                        estadoCita = 3;
                    }
            }
            
        switch(estadoCita){
            case 0:
                return "Vencida";
            case 1:
                return "En curso";
            case 2:
                return "Aplicada";    
            case 3:
                return "Cancelada";
            default:
                return "-";
            }
    }
    
    private void ordenarArray() {
    Collections.sort(lista_citas, new Comparator<CitaVacunacion>() {
        @Override
        public int compare(CitaVacunacion cita1, CitaVacunacion cita2) {
            return cita1.getHorario().compareTo(cita2.getHorario());
        }
    });
    }
}

