/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Elio Flores
 */
public class TurnosABM extends javax.swing.JFrame {

  /**
   * Creates new form TurnosABM
   */
  public TurnosABM() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    codCitaLabel = new javax.swing.JLabel();
    codigoCita = new javax.swing.JTextField();
    buscar = new javax.swing.JButton();
    dniLabel = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jComboBox1 = new javax.swing.JComboBox<>();
    dniLabel1 = new javax.swing.JLabel();
    jTextField2 = new javax.swing.JTextField();
    dniLabel2 = new javax.swing.JLabel();
    jTextField3 = new javax.swing.JTextField();
    jTextField4 = new javax.swing.JTextField();
    dniLabel3 = new javax.swing.JLabel();
    dniLabel4 = new javax.swing.JLabel();
    jTextField5 = new javax.swing.JTextField();
    dniLabel5 = new javax.swing.JLabel();
    jTextField6 = new javax.swing.JTextField();
    jComboBox2 = new javax.swing.JComboBox<>();
    jLabel2 = new javax.swing.JLabel();
    dniLabel6 = new javax.swing.JLabel();
    jTextField7 = new javax.swing.JTextField();
    jTextField8 = new javax.swing.JTextField();
    jTextField9 = new javax.swing.JTextField();
    jTextField10 = new javax.swing.JTextField();
    jTextField11 = new javax.swing.JTextField();
    jTextField12 = new javax.swing.JTextField();
    dniLabel7 = new javax.swing.JLabel();
    dniLabel8 = new javax.swing.JLabel();
    dniLabel9 = new javax.swing.JLabel();
    dniLabel10 = new javax.swing.JLabel();
    dniLabel11 = new javax.swing.JLabel();
    jTextField13 = new javax.swing.JTextField();
    dniLabel12 = new javax.swing.JLabel();
    jTextField14 = new javax.swing.JTextField();
    dniLabel13 = new javax.swing.JLabel();
    dniLabel14 = new javax.swing.JLabel();
    jTextField15 = new javax.swing.JTextField();
    dniLabel15 = new javax.swing.JLabel();
    jTextField16 = new javax.swing.JTextField();
    jComboBox3 = new javax.swing.JComboBox<>();
    jLabel4 = new javax.swing.JLabel();
    dniLabel16 = new javax.swing.JLabel();
    jTextField17 = new javax.swing.JTextField();
    dniLabel17 = new javax.swing.JLabel();
    jTextField18 = new javax.swing.JTextField();
    jTextField19 = new javax.swing.JTextField();
    dniLabel18 = new javax.swing.JLabel();
    dniLabel19 = new javax.swing.JLabel();
    jTextField20 = new javax.swing.JTextField();
    separador3 = new javax.swing.JSeparator();
    separador4 = new javax.swing.JSeparator();
    separador1 = new javax.swing.JSeparator();
    titulo = new javax.swing.JLabel();
    separador2 = new javax.swing.JSeparator();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    codCitaLabel.setText("Codigo cita");
    jPanel1.add(codCitaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));
    jPanel1.add(codigoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 260, -1));

    buscar.setText("Buscar");
    jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));

    dniLabel.setText("Nombre y apellido:");
    jPanel1.add(dniLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));
    jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 110, -1));

    jLabel1.setText("Ciudadano:");
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 400, -1));

    dniLabel1.setText("DNI:");
    jPanel1.add(dniLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));
    jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 110, -1));

    dniLabel2.setText("Email:");
    jPanel1.add(dniLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
    jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 110, -1));
    jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 110, -1));

    dniLabel3.setText("Celular:");
    jPanel1.add(dniLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

    dniLabel4.setText("Patologia:");
    jPanel1.add(dniLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));
    jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 110, -1));

    dniLabel5.setText("Ambito de trabajo:");
    jPanel1.add(dniLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));
    jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 110, -1));

    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 400, -1));

    jLabel2.setText("Vacuna");
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

    dniLabel6.setText("Nro de serie:");
    jPanel1.add(dniLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));
    jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 110, -1));
    jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 110, -1));
    jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 110, -1));
    jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 110, -1));
    jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 110, -1));
    jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 110, -1));

    dniLabel7.setText("Fecha de caducidad:");
    jPanel1.add(dniLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

    dniLabel8.setText("Marca:");
    jPanel1.add(dniLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

    dniLabel9.setText("Ambito de trabajo:");
    jPanel1.add(dniLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));

    dniLabel10.setText("Colocada");
    jPanel1.add(dniLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

    dniLabel11.setText("Medida:");
    jPanel1.add(dniLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));
    jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 110, -1));

    dniLabel12.setText("Pais:");
    jPanel1.add(dniLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, -1, -1));
    jPanel1.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 110, -1));

    dniLabel13.setText("Domicilio:");
    jPanel1.add(dniLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

    dniLabel14.setText("Laboratorio:");
    jPanel1.add(dniLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));
    jPanel1.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 110, -1));

    dniLabel15.setText("CUIT:");
    jPanel1.add(dniLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, -1, -1));
    jPanel1.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 110, -1));

    jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 660, 100, -1));

    jLabel4.setText("Centro de vacunacion:");
    jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, -1, -1));

    dniLabel16.setText("Codigo de refuerzo:");
    jPanel1.add(dniLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, -1));
    jPanel1.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, 110, -1));

    dniLabel17.setText("Marca:");
    jPanel1.add(dniLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 580, -1, -1));
    jPanel1.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 580, 110, -1));
    jPanel1.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, 110, -1));

    dniLabel18.setText("Caducidad:");
    jPanel1.add(dniLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 620, -1, -1));

    dniLabel19.setText("Colocacion:");
    jPanel1.add(dniLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, -1, -1));
    jPanel1.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 620, 110, -1));
    jPanel1.add(separador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 560, 10));
    jPanel1.add(separador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 560, 10));
    jPanel1.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 560, 10));

    titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    titulo.setText("Administracion de citas de vacunacion");
    jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));
    jPanel1.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 560, 10));

    jButton1.setText("Nuevo");
    jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 80, -1));

    jButton2.setText("Guardar");
    jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 80, -1));

    jButton3.setText("Modificar");
    jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 80, -1));

    jButton4.setText("Eliminar");
    jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 80, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TurnosABM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TurnosABM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TurnosABM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TurnosABM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TurnosABM().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buscar;
  private javax.swing.JLabel codCitaLabel;
  private javax.swing.JTextField codigoCita;
  private javax.swing.JLabel dniLabel;
  private javax.swing.JLabel dniLabel1;
  private javax.swing.JLabel dniLabel10;
  private javax.swing.JLabel dniLabel11;
  private javax.swing.JLabel dniLabel12;
  private javax.swing.JLabel dniLabel13;
  private javax.swing.JLabel dniLabel14;
  private javax.swing.JLabel dniLabel15;
  private javax.swing.JLabel dniLabel16;
  private javax.swing.JLabel dniLabel17;
  private javax.swing.JLabel dniLabel18;
  private javax.swing.JLabel dniLabel19;
  private javax.swing.JLabel dniLabel2;
  private javax.swing.JLabel dniLabel3;
  private javax.swing.JLabel dniLabel4;
  private javax.swing.JLabel dniLabel5;
  private javax.swing.JLabel dniLabel6;
  private javax.swing.JLabel dniLabel7;
  private javax.swing.JLabel dniLabel8;
  private javax.swing.JLabel dniLabel9;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JComboBox<String> jComboBox1;
  private javax.swing.JComboBox<String> jComboBox2;
  private javax.swing.JComboBox<String> jComboBox3;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField10;
  private javax.swing.JTextField jTextField11;
  private javax.swing.JTextField jTextField12;
  private javax.swing.JTextField jTextField13;
  private javax.swing.JTextField jTextField14;
  private javax.swing.JTextField jTextField15;
  private javax.swing.JTextField jTextField16;
  private javax.swing.JTextField jTextField17;
  private javax.swing.JTextField jTextField18;
  private javax.swing.JTextField jTextField19;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextField jTextField20;
  private javax.swing.JTextField jTextField3;
  private javax.swing.JTextField jTextField4;
  private javax.swing.JTextField jTextField5;
  private javax.swing.JTextField jTextField6;
  private javax.swing.JTextField jTextField7;
  private javax.swing.JTextField jTextField8;
  private javax.swing.JTextField jTextField9;
  private javax.swing.JSeparator separador1;
  private javax.swing.JSeparator separador2;
  private javax.swing.JSeparator separador3;
  private javax.swing.JSeparator separador4;
  private javax.swing.JLabel titulo;
  // End of variables declaration//GEN-END:variables
}
